name: Publish to the CubeEngine Maven Repository
on:
    push:
        branches: [ api-* ]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Publish package
              run: ./gradlew build updateGithubRelease --continue --parallel -PgithubApiToken=${{ secrets.GITHUB_TOKEN }}
