name: Publish to the CubeEngine Maven Repository
on:
    push:
        branches: [ api-* ]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 17
            - name: Publish package
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: publish --continue
                  gradle-version: wrapper
              env:
                  cubyteUsername: ${{ secrets.NEXUS_USER }}
                  cubytePassword: ${{ secrets.NEXUS_PASS }}
